# Generated by Django 3.0.4 on 2020-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_subtype', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('dt', models.DateTimeField(verbose_name='date of occurrence')),
            ],
        ),
    ]
